const GITHUB_AUTH_TOKEN = "null"
const BOT_NUMBER = "null"
const SESSION_ID = "PRABATH-MD~VJ5yVaQK#wFzEDasCQQB3cCATkERXG6AyUKJWLo9aR6pEtPsGarU"


module.exports = {
GITHUB_AUTH_TOKEN,
BOT_NUMBER,
SESSION_ID
}
